apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: membersservice-deployment
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: membersservice-deployment
  targetCPUUtilizationPercentage: 80


