apiVersion: v1
kind: Service
metadata:
  name: agreementsservice-service
spec:
  selector:
    app: AgreementsService
  ports:
    - protocol: TCP
      port: 84
      targetPort: 5004
  clusterIP: 10.96.0.14