apiVersion: v1
kind: Service
metadata:
  name: messagebus-service
spec:
  #clusterIP: 10.96.0.7
  selector:
    app: MessageBus
  ports:
    - name: port8080
      protocol: TCP
      port: 8080
      targetPort: 5672
    - name: port80
      protocol: TCP
      port: 80
      targetPort: 15672 
  clusterIP: 10.96.0.10
  type: LoadBalancer
      