apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment-as
spec:
  selector:
    matchLabels:
      app: mssql-as
  replicas: 1
  template:
    metadata:
      labels:
        app: mssql-as
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mssql-as
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbs-secret
                  key: SA_PASSWORD
          volumeMounts:
            - name: mssqldb
              mountPath: /var/opt/mssql
      volumes:
        - name: mssqldb
          persistentVolumeClaim:
            claimName: pvc-mssql-fitverse-as
