kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mssql-fitverse-storage-class
provisioner: kubernetes.io/azure-disk
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  kind: Managed