apiVersion: v1
kind: Service
metadata:
  name: classesservice-service
spec:
  clusterIP: 10.96.0.3
  selector:
    app: ClassesService
  ports:
    - name: port8080
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: port80
      protocol: TCP
      port: 60
      targetPort: 80
      