apiVersion: v1
kind: Service
metadata:
  name: fitverseclient-service
spec:
  clusterIP: 10.96.0.4
  selector:
    app: FitverseClient
  ports:
    - name: port8080
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: port80
      protocol: TCP
      port: 80
      targetPort: 80
      