apiVersion: v1
kind: Service
metadata:
  name: membersservice-service      #Service name
spec:
  clusterIP: 10.96.0.6              #IP of service, it have to be in the range of IPv4 or IPv6
  selector:
    app: MembersService             #Field defines how the service finds which pods to connect with this service 
  ports:                            #Fields define ports of this service
    - name: port8080
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: port80
      protocol: TCP
      port: 80
      targetPort: 80