apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailingservice-deployment
  labels:
    app: MailingService
    name: mailingservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: MailingService

 #-------------------------------> RollingUpdate definition
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 50%

#-------------------------------> Blueprint for Pod
  template:
    metadata:
      labels:
        app: MailingService
    spec:
      containers:
      - name: mailingservice
        image: fitverse/testpublicenv:latest
        ports:
        - containerPort: 8080
        - name: health-port
          containerPort: 80
         #hostPort: 80

#-------------------------------> startupProbe definiton
        startupProbe:
          httpGet:
            path: /api/checktrue
            port: health-port
          failureThreshold: 30
          periodSeconds: 10

#------------------------> ReadinessProbe  for healthcheck
        readinessProbe:                    
          httpGet:
            path: /api/checktrue
            port: health-port
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 20
          successThreshold: 5
          failureThreshold: 3