apiVersion: v1
kind: Secret
metadata:
  name: dbs-secret
type: Opaque
Data:
  #MembersService Database ConnectionString
  MS_DB_ConnectionString: mssql-ms-service.default.svc.cluster.local,1434
  MS_DB_INITIAL_CATALOG: fitverse-member-db
  MS_DB_USER: sa


  #AgreementService Database ConnectionString
  AS_DB_ConnectionString: mssql-as-service.default.svc.cluster.local,1433
  AS_DB_INITIAL_CATALOG: fitverse-member-db
  AS_DB_USER: sa
